# Generated by Django 4.0.2 on 2022-02-25 16:22

import arike_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', arike_app.models.CustomUserManager()),
            ],
        ),
    ]
