# Generated by Django 4.0.2 on 2022-03-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='care_sub_type',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='care_type',
        ),
        migrations.RemoveField(
            model_name='treatmentnotes',
            name='care_sub_type',
        ),
        migrations.RemoveField(
            model_name='treatmentnotes',
            name='care_type',
        ),
        migrations.AddField(
            model_name='treatment',
            name='care_type_and_sub_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='arike_app.caresubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentnotes',
            name='care_type_and_sub_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='arike_app.caresubtype'),
            preserve_default=False,
        ),
    ]
