# Generated by Django 4.0.2 on 2022-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0002_remove_treatment_care_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.facility'),
        ),
    ]
