# Generated by Django 4.0.2 on 2022-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0002_alter_disease_created_at_alter_disease_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetail',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
