# Generated by Django 4.0.2 on 2022-03-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0003_alter_familydetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familydetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
