# Generated by Django 4.0.2 on 2022-02-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0004_alter_user_district_alter_user_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'District Admin'), (2, 'Doctor'), (3, 'Primary Nurse'), (4, 'Secondary Nurse')], null=True),
        ),
    ]
