# Generated by Django 4.0.2 on 2022-03-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0004_visitschedule_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentnotes',
            name='care_type_and_sub_type',
        ),
    ]
