# Generated by Django 4.0.2 on 2022-03-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0004_alter_familydetail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetail',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.patient'),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.patient'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.patient'),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.patient'),
        ),
    ]
