# Generated by Django 4.0.2 on 2022-02-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
