# Generated by Django 4.0.2 on 2022-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0005_alter_familydetail_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='palliative_phase',
            field=models.IntegerField(choices=[(1, 'Stable'), (2, 'Unstable'), (3, 'Deteriorating'), (4, 'Dying')]),
        ),
    ]
