# Generated by Django 4.0.2 on 2022-03-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0006_alter_treatment_treatment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='visit_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='arike_app.visitschedule'),
        ),
    ]
