# Generated by Django 4.0.2 on 2022-02-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0006_rename_full_name_patient_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
