# Generated by Django 4.0.2 on 2022-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0006_alter_visitdetails_palliative_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='systemic_examination_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='systemic_examination',
            field=models.IntegerField(choices=[(1, 'Stable'), (2, 'Unstable'), (3, 'Deteriorating'), (4, 'Dying')]),
        ),
    ]
