# Generated by Django 4.0.2 on 2022-03-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0007_visitdetails_systemic_examination_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitdetails',
            old_name='note',
            new_name='notes',
        ),
    ]
