# Generated by Django 4.0.2 on 2022-02-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0007_patient_email_patient_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
