# Generated by Django 4.0.2 on 2022-03-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0008_userreportconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_notes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='arike_app.treatmentnotes'),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='treatment_notes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='arike_app.treatmentnotes'),
        ),
    ]
