# Generated by Django 4.0.2 on 2022-03-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0008_rename_note_visitdetails_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('value', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('care_sub_type', models.TextField(max_length=255)),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arike_app.caretype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
