# Generated by Django 4.0.2 on 2022-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arike_app', '0009_alter_treatment_treatment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentnotes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentnotes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='general_random_blood_sugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='mouth_hygiene',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='pain',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='palliative_phase',
            field=models.IntegerField(choices=[(1, 'Stable'), (2, 'Unstable'), (3, 'Deteriorating'), (4, 'Dying')], null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='patient_at_peace',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='personal_hygiene',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='public_hygiene',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='pulse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='systemic_examination',
            field=models.IntegerField(choices=[(1, 'Stable'), (2, 'Unstable'), (3, 'Deteriorating'), (4, 'Dying')], null=True),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='systemic_examination_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
